ReportSystem/Models/Option.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportSystem.Models;

public class Option
{
    [Key, Column("OptionId")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid OptionId { get; set; }
    
    [Required]
    public string? OptionName { get; set; }
    [Required]
    public int Urgency { get; set; }

    /*[Key]
    [Column("PointId")]
    [ForeignKey("PointId")]*/
    public Guid PointId { get; set; }

    public Point? Point { get; set; }
    
    [NotMapped]
    public virtual ICollection<Notice>? Notice { get; set; }
    
}

ReportSystem/Pages/Options/AddOptions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.Options;

public class AddOptions : PageModel
{
    private readonly CrudRepository _crudRepository;


    public AddOptions(CrudRepository crudRepository)
    {
        _crudRepository = crudRepository;
        _Points = _crudRepository.ReadAllRows<Point>().Result.ConvertAll(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.PointId.ToString()
        });
    }
    
    public List<SelectListItem>? _Points { get; set; }
    [BindProperty] public Option? Option { get; set; }
    
    public async Task<IActionResult> OnPostAddOption()
    {
        
        if (ModelState.IsValid)
        {
            await _crudRepository.AddRow(Option);
        }
        return RedirectToPage("/Options/OptionsOverview");
    }
}


ReportSystem/Pages/Options/OptionsOverview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.Options;

public class OptionsOverview : PageModel
{
    private readonly CrudRepository _crudRepository;
    private readonly UserRepository _userRepository;


    public OptionsOverview(CrudRepository crudRepository, UserRepository userRepository)
    {
        _crudRepository = crudRepository;
        _userRepository = userRepository;
        _Options = crudRepository.ReadAllRows<Option>().Result;
        _Points = crudRepository.ReadAllRows<Point>().Result;
    }
    
    
    [BindProperty] public Point? Point { get; set; }
    [BindProperty] public Option? Option { get; set; }

    public List<Option>? _Options { get; set; }
    
    public List<Point>? _Points { get; set; }

    public async Task<IActionResult> OnPostUpdateOption()
    {
        if (_Options != null)
        {
            await _crudRepository.UpdateRow(Option);
        }
        return RedirectToPage("/Options/OptionsOverview");
    }
    public async Task<IActionResult> OnPostDeleteOption()
    {
        if (_Options != null)
        {
            await _crudRepository.RemoveRow(_Options.First(x => Option != null && x.OptionId == Option.OptionId));
            _Options.RemoveAll(x => Option != null && x.OptionId == Option.OptionId);
        }

        return RedirectToPage("/Options/OptionsOverview");

    }
}

ReportSystem/Pages/Options/AddOptions.cshtml
@page
@model ReportSystem.Pages.Options.AddOptions

<div class="container">
    <div class="row">
        <div class="col-md">
            <form method="post" asp-page-handler="AddOption">
                <select class="form-select" asp-for="Option!.PointId" asp-items="Model._Points">
                </select>
                <input type="hidden"/>
                <div class="form-group">
                    <label asp-for="Option!.OptionName"></label>
                    <input asp-for="Option!.OptionName" type="text" class="form-control" placeholder="Vul optie in.">
                </div>
                <div class="form-group">
                    <label asp-for="Option!.Urgency"></label>
                    <select name="Urgentie" asp-for="Option!.Urgency">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Voeg optie toe.</button>
                </div>
            </form>
        </div>
    </div>

</div>

ReportSystem/Pages/Options/OptionsOverview.cshtml
@page
@using ReportSystem.Repositories
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ReportSystem.Models
@model ReportSystem.Pages.Options.OptionsOverview

@inject UserRepository _userRepository
@{
    var loggedIn = _userRepository.IsUserLoggedIn();
}

@if (loggedIn)
{
    <div class="container">
        <div class="row">
            @if (Model._Points != null)
            {
                @foreach (var point in Model._Points)
                {
                    <form method="post">
                        <input type="hidden" asp-for="Point!.PointId" value="@point.PointId"/>
                    </form>

                    <ul class="list-group">
                        @if (Model._Options != null)
                        {
                            foreach (var option in Model._Options)
                            {
                                if (option.PointId == point.PointId)
                                {
                                    <form method="post">
                                        <input type="hidden" asp-for="Option!.OptionId" value="@option.OptionId"/>
                                        <li class="list-group-item">
                                            <label>@point.Name</label>
                                            <label>Opties</label>
                                            <input type="text" asp-for="Option!.OptionName" value="@option.OptionName"/>
                                            <select name="Urgentie" asp-for="Option!.Urgency">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                            </select>
                                            <input type="hidden" asp-for="Option!.PointId" value="@option.PointId"/>
                                            <button type="submit" asp-page-handler="UpdateOption" class="btn btn-primary">Wijzig optie</button>
                                            <button type="submit" asp-page-handler="DeleteOption" class="btn btn-danger">Verwijder optie</button>
                                        </li>
                                    </form>
                                }
                            }
                        }
                    </ul>
                }
            }
        </div>
    </div>
}