ReportSystem/Pages/Punten/AddPoint.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.Punten;


public class AddPoint : PageModel
{
    private readonly CrudRepository _crudRepository;
    private readonly UserRepository _userRepository;


    public AddPoint(CrudRepository crudRepository, UserRepository userRepository)
    {
        _crudRepository = crudRepository;
        _userRepository = userRepository;
    }

    
    
    [BindProperty] public Point? Point { get; set; }

    public Option? Option { get; set; } = new Option();

    public async Task<IActionResult> OnPostAddPoint()
    {
        
        Point.ApplicationUserId = _userRepository.GetCurrentUserId();
        if (ModelState.IsValid)
        {
            Guid pointId = Guid.NewGuid();
            Point.PointId = pointId;
            await _crudRepository.AddRow(Point);
            Option.OptionName = "Anders";
            Option.Urgency = 3;
            Option.PointId = Point.PointId;
            
            await _crudRepository.AddRow(Option);
            return Redirect("/qrcode?PointId=" + pointId);
        }
        return Page();
    }
    
}

ReportSystem/Pages/Punten/PointsOverview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.Punten;

public class PointsOverview : PageModel
{
    private readonly CrudRepository _crudRepository;
    private readonly UserRepository _userRepository;


    public PointsOverview(CrudRepository crudRepository, UserRepository userRepository)
    {
        _crudRepository = crudRepository;
        _userRepository = userRepository;
        _Points = crudRepository.ReadAllRows<Point>().Result;
    }

    [BindProperty] public Point? Point { get; set; }

    public List<Point>? _Points { get; set; }

    public async Task<IActionResult> OnPostUpdatePoint()
    {
        if (_Points != null)
        {
            await _crudRepository.UpdateRow(Point);
        }
        return RedirectToPage("/Punten/PointsOverview");
    }
    public async Task<IActionResult> OnPostDeletePoint()
    {
        if (_Points != null)
        {
            await _crudRepository.RemoveRow(_Points.First(x => Point != null && x.PointId == Point.PointId));
            _Points.RemoveAll(x => Point != null && x.PointId == Point.PointId);
        }

        return RedirectToPage("/Punten/PointsOverview");

    }

    public async Task<IActionResult> OnPostQr()
    {
        return Redirect("/qrcode?PointId=" + Point.PointId);
    }
}
    

ReportSystem/Pages/Punten/AddPoint.cshtml
@page
@model ReportSystem.Pages.Punten.AddPoint

<div class="container">
    <div class="row">
        <div class="col-md">
            <form method="post" asp-page-handler="AddPoint">
                <input type="hidden"/>
                <div class="form-group">
                    <label asp-for="Point!.Name"></label>
                    <input asp-for="Point!.Name" type="text" class="form-control" placeholder="Vul meldingspunt in.">
                    <input type="hidden" asp-for="Option.OptionName" value="Anders"/>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Voeg Point toe.</button>
                </div>
            </form>
        </div>
    </div>
    
</div>

ReportSystem/Pages/Punten/PointsOverview.cshtml
@page
@using ReportSystem.Repositories
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ReportSystem.Pages.Punten.PointsOverview
@inject UserRepository _userRepository
@{
    var loggedIn = _userRepository.IsUserLoggedIn();
}

@if (loggedIn)
{
    <ul class="list-group">
        @if (Model._Points != null)
        {
            foreach (var point in Model._Points)
            {
                <form method="post">
                    <input type="hidden" asp-for="Point!.PointId" value="@point.PointId"/>
                    <li class="list-group-item">
                        <label>Meldingspunt</label>
                        <input type="text" asp-for="Point!.Name" value="@point.Name"/>
                        <input type="hidden" asp-for="Point!.PointId" value="@point.PointId"/>
                        <button type="submit" asp-page-handler="UpdatePoint" class="btn btn-primary">Wijzig meldingspunt</button>
                        <button type="submit" asp-page-handler="DeletePoint" class="btn btn-danger">Verwijder meldingspunt</button>
                        <button type="submit" asp-page-handler="Qr" class="btn btn-secondary">Zie Qrcode</button>

                    </li>

                </form>
            }
        }
    </ul>
}