ReportSystem/Pages/Melding/Meldingen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.Melding;

public class Meldingen : PageModel
{
    private readonly CrudRepository _crudRepository;
    private readonly bool succeeded;
    public readonly Guid PointId;
    public Point? Point { get; set; }

    public Meldingen(CrudRepository crudRepository, IHttpContextAccessor httpContext)
    {
        _crudRepository = crudRepository;
        succeeded = GeneralRepository.parseId(httpContext, out PointId);

        Point = crudRepository.FindRow<Point>(x => x.PointId == PointId).Result;

        _Options = _crudRepository.ReadAllRows<Option>().Result.ConvertAll(x => new SelectListItem()
        {
            Text = x.OptionName,
            Value = x.PointId.ToString()
        });
        _Notices = crudRepository.ReadAllRows<Notice>().Result;
        _options = crudRepository.ReadAllRows<Option>().Result;
        _Points = crudRepository.ReadAllRows<Point>().Result;

        List<Option> _pointoptions = new List<Option>();
        foreach (var option in _options)
        {
            if (option.PointId == Point.PointId)
            {
                _pointoptions.Add(option);
            }
        }

        _PointOptions = _pointoptions.ConvertAll(a =>
        {
            return new SelectListItem()
            {
                Text = a.OptionName,
                Value = a.OptionId.ToString(),
                Selected = false
            };
        });
    }


    public Option? Option { get; set; }
    [BindProperty] public Notice? Notice { get; set; }
    public List<SelectListItem>? _Options { get; set; }
    public List<SelectListItem>? _PointOptions { get; set; }
    public List<Notice>? _Notices { get; set; }
    public List<Option>? _options { get; set; }
    public List<Point>? _Points { get; set; }


    public async Task<IActionResult> OnPostAddMelding()
    {
        if (ModelState.IsValid)
        {
            await _crudRepository.AddRow(Notice);
        }

        return Redirect("/Melding/Meldingen?PointId=" + PointId);
    }
}

ReportSystem/Pages/Melding/MeldingenOverview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ReportSystem.DB;
using ReportSystem.Models;
using ReportSystem.Repositories;
using System;

namespace ReportSystem.Pages
{
    public class MeldingenOverview : PageModel
    {
        private readonly CrudRepository _crudRepository;
        private readonly UserRepository _userRepository;
        public MeldingenOverview(AuthDbContext context, CrudRepository crudRepository, UserRepository userRepository)
        {
            _crudRepository = crudRepository;
            _userRepository = userRepository;
            _Options = crudRepository.ReadAllRows<Option>().Result;
            _Points = crudRepository.ReadAllRows<Point>().Result;
            _Notices = crudRepository.ReadAllRows<Notice>().Result;
        }
       

        [BindProperty] public Notice? Notice { get; set; }

        public List<Option>? _Options { get;set; }
        public List<Notice>? _Notices { get;set; }
        public List<Point>? _Points { get; set; }

        public async Task<IActionResult> OnPostDelteMelding()
        {
            if(_Notices != null)
            {
                var notice = _Notices.FirstOrDefault(x => Notice != null && x.NoticeId == Notice.NoticeId);
                await _crudRepository.RemoveRow(notice);
            }
            return RedirectToPage("/Melding/MeldingenOverview");
        }
        
    }
}

ReportSystem/Pages/Melding/Meldingen.cshtml
@page
@using ReportSystem.Repositories
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ReportSystem.Models
@model ReportSystem.Pages.Melding.Meldingen


<div class="container">
    <div class="card text-center">
        <div class="row">
            <h1>Melding maken van punt: @Model.Point.Name</h1>
        </div>
    </div>
    <div class="card row justify-content-center">
        <div class="container text-center">

            @if (Model.Point != null)
            {
                <form method="post" asp-page-handler="AddMelding" asp-route-PointId="@Model.PointId">
                    <select class="form-select" asp-for="Notice!.OptionId" asp-items="Model._PointOptions">
                    </select>
                    <input asp-for="Notice!.Description" type="text" class="form-control" placeholder="Omschrijf melding">
                    DateTime: <input asp-for="Notice.DateTime"/>
                    <button type="submit" class="btn btn-primary">Voeg melding toe.</button>

                </form>
            }


            @if (@Model._Notices != null)
            {
                foreach (var option in @Model._options)
                {
                    foreach (var notice in @Model._Notices)
                    {
                        if (notice.OptionId == option.OptionId)
                        {
                            <div class="card">
                                <li class="list-group-item">
                                    <i>@Model.Point.Name</i>
                                    <i>@option.OptionName</i>
                                    <i>@notice.Description</i>
                                    <i>@notice.DateTime</i>
                                </li>
                            </div>
                        }
                    }
                }
            }
        </div>
    </div>
</div>

ReportSystem/Pages/Melding/MeldingenOverview.cshtml
@page
@using ReportSystem.Repositories;
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ReportSystem.Models
@model ReportSystem.Pages.MeldingenOverview

@inject UserRepository _userRepository
@{
    var loggedIn = _userRepository.IsUserLoggedIn();
}

@if (loggedIn)
{
    <div class="container">
        <div class="row">
            @if(Model._Notices != null)
            {
                @if (Model._Points != null)
                {
                    @foreach (var point in Model._Points)
                    {
                        <ul class="list-group">
                            @if (Model._Options != null)
                            {
                                foreach (var option in Model._Options)
                                {
                                    if (option.PointId == point.PointId)
                                    {
                                        foreach (var notice in Model._Notices)
                                        {
                                            if (notice.OptionId == option.OptionId)
                                            {
                                        <form method="post">
                                         <input type="hidden" asp-for="Notice!.NoticeId" value="@notice.NoticeId" />
                                                <li class="list-group-item">
                                                    <i>@notice.Description</i>
                                                    <i>@notice.DateTime</i>
                                                    <i>@option.Urgency</i>
                                                    <i>@point.Name</i>
                                                        <button type="submit" asp-page-handler="DelteMelding" class="btn btn-danger">Verwijder optie</button>
                                                </li>
                                          </form>
                                            }
                                        }
                                    }
                                }
                            }
                        </ul>
                    }
                }
            }else
            {
                <h1>Er zijn geen meldingen</h1>
            }

        </div>
    </div>
}