ReportSystem/Pages/User/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.User;

public class Login : PageModel
{
    private readonly UserRepository _userRepository;

    public Login(UserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    [BindProperty] public LoginUser? LoginUser { get; set; }

    public async Task<IActionResult> OnPost()
    {
        if (ModelState.IsValid)
        {
            var result = await _userRepository.Login(LoginUser);

            if (result.Succeeded)
                return RedirectToPage("/Index");
        }
        ModelState.AddModelError("", "Gebruikersnaam of Wachtwoord is incorrect");
    
        return Page();
    }

}

ReportSystem/Pages/User/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.User;

public class Logout : PageModel
{
    private readonly UserRepository _userRepository;

    public Logout(UserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    public async Task<IActionResult> OnPostLogoutAsync()
    {
        await _userRepository.Logout();
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostDontLogoutAsync()
    {
        return RedirectToPage("/Index");
    }
}

ReportSystem/Pages/User/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ReportSystem.Models;
using ReportSystem.Repositories;

namespace ReportSystem.Pages.User;

public class Register : PageModel
{
    private readonly UserRepository _userRepository;

    public Register(UserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    [BindProperty] public RegisterUser RegisterUser { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (!ModelState.IsValid) return Page();

        var result = await _userRepository.RegisterUser(RegisterUser);


        if (!result.Succeeded)
        {
            result.Errors.ToList().ForEach(x =>
                ModelState.AddModelError("", x.Description ?? "Er is helaas iets mis gegaan."));
            return Page();
        }

        else
        {
            return RedirectToPage("/User/Login");
        }
    }
}

ReportSystem/Pages/User/Login.cshtml
@page
@model ReportSystem.Pages.User.Login

@{
    ViewData["Title"] = "Login";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div asp-validation-summary="ModelOnly"></div>
            <form method="post">
                <div class="form-group">
                    <label asp-for="LoginUser.UserName"></label>
                    <input asp-for="LoginUser.UserName" type="text" class="form-control" id="username" aria-label="username" aria-describedby="basic-addon1" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label asp-for="LoginUser.Password"></label>
                    <input asp-for="LoginUser.Password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="form-check">
                    <input  asp-for="LoginUser.rememberMe" type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label asp-for="LoginUser.rememberMe" class="form-check-label" for="exampleCheck1"></label>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>

ReportSystem/Pages/User/Logout.cshtml
@page
@model ReportSystem.Pages.User.Logout


<div class="row justify-content-center">

    <div class="card col-sm-12 col-md-6">
        <div class="card-body align-items-center justify-content-center">

            <h1 class="display-4">Are you sure you want to logout?</h1><br/><hr/>


            <form method="post" class="row flex-row-reverse">
                <button class="btn btn-lg btn-outline-primary col-5 m-1" asp-page-handler="DontLogout">Cancel</button>
                <button class="btn btn-lg btn-outline-danger col-6 m-1" asp-page-handler="Logout">Logout</button>
            </form>


        </div>
    </div>

</div>

ReportSystem/Pages/User/Register.cshtml
@page
@model ReportSystem.Pages.User.Register

@{
    ViewData["Title"] = "Registreer";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div asp-validation-summary="ModelOnly"></div>
            <form method="post">
                <div class="form-group">
                    <label asp-for="RegisterUser.UserName"></label>
                    <input asp-for="RegisterUser.UserName" type="text" class="form-control" id="username" aria-label="username" aria-describedby="basic-addon1" placeholder="Enter username">
                    <span asp-validation-for="RegisterUser.UserName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RegisterUser.Password"></label>
                    <input asp-for="RegisterUser.Password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    <span asp-validation-for="RegisterUser.Password"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RegisterUser.Email"></label>
                    <input asp-for="RegisterUser.Email" type="text" class="form-control" placeholder="some@email.com">
                    <span asp-validation-for="RegisterUser.Email"></span>
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
    </div>
</div>